CREATE TABLE cliente(
id BIGINT NOT NULL AUTO_INCREMENT,
nome VARCHAR(30) NOT NULL,
email VARCHAR(30) NOT NULL UNIQUE ,
cpf VARCHAR(15) NOT NULL UNIQUE,
telefone VARCHAR(30),

bairro VARCHAR(30),
cidade VARCHAR(25),
logradouro VARCHAR(30),
cep VARCHAR(10),
numero VARCHAR(4),

PRIMARY KEY (id) 
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4;